### ISSUE TITLE
Make it an Awesome-List

### ISSUE THREAD

**Issue by anuraghazra** [askbuddie/vulnerabilities#3]
i don't no anything about Computer Security but i would like to suggest this kind of list should be a awesome-list

Further Resources
- https://github.com/topics/awesome-list
- https://github.com/sindresorhus/awesome
- https://github.com/s0md3v/AwesomeXSS
- https://github.com/sbilly/awesome-security

**Comment by Aju100** [comment]
Yeah  @anuraghazra

**Comment by ashiishme** [comment]
Sure
